GestionMusiques/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('musiques/', include('musiques.urls')),
]

from django.conf import settings

if settings.DEBUG:
   import debug_toolbar
   urlpatterns += [
       path('__debug__/', include(debug_toolbar.urls)),
   ]

musiques/urls.py
from django.urls import path
#from .views import morceau_detail
from .views import MorceauDetailView, MorceauList, MorceauCreate, MorceauDelete, MorceauUpdate
from .views import ArtisteDetailView, ArtisteList, ArtisteCreate, ArtisteDelete, ArtisteUpdate
app_name = 'musiques'

urlpatterns = [
    #path('<int:pk>', morceau_detail, name='morceau-detail')
    path('<int:pk>', MorceauDetailView.as_view(), name='morceau-detail'),
    path('', MorceauList.as_view(), name='morceau_list'),
    path('morceau', MorceauCreate.as_view(), name='morceau_create'),
    path('<int:pk>/delete/', MorceauDelete.as_view(), name='morceau-delete'),
    path('morceau/<int:pk>', MorceauUpdate.as_view(), name='morceau_update'),
    #path('<int:pk>', morceau_detail, name='morceau-detail')
    path('artiste/<int:pk>', ArtisteDetailView.as_view(), name='artiste-detail'),
    path('artiste', ArtisteList.as_view(), name='artiste_list'),
    path('artiste/new', ArtisteCreate.as_view(), name='artiste_create'),
    path('artiste/<int:pk>/delete/', ArtisteDelete.as_view(), name='artiste-delete'),
    path('artiste/<int:pk>/update', ArtisteUpdate.as_view(), name='artiste_update'),
 ]

musiques/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Artiste(models.Model):
    nom = models.CharField(max_length=64)
    def __str__(self):
        return self.nom

    def get_absolute_url(self):
        return reverse('musiques:artiste-detail', kwargs={'pk': self.pk})
    
    def nombre_morceaux(self):
        return self.morceaux.count()

class Morceau(models.Model):
    titre = models.CharField(max_length=64)
    #artiste = models.CharField(max_length=64)
    date_sortie = models.DateField(null=True)
    interprete = models.ForeignKey(Artiste, on_delete=models.CASCADE, related_name="morceaux", null=True)

    def __str__(self):
        return '{self.titre} ({self.interprete.nom})'.format(self=self)

    def get_absolute_url(self):
        return reverse('musiques:morceau-detail', kwargs={'pk': self.pk})

musiques/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Morceau, Artiste
from django.views.generic import DetailView, ListView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

def morceau_detail(request, pk):
    morceau = Morceau.objects.get(pk=pk)
    return HttpResponse(str(morceau))

class MorceauDetailView(DetailView):
    model = Morceau

class MorceauList(ListView):
    model = Morceau

class MorceauCreate(CreateView):
    model = Morceau
    fields = ['titre', 'interprete']

class MorceauDelete(DeleteView):
    model = Morceau
    success_url = reverse_lazy('musiques:morceau_list')

class MorceauUpdate(UpdateView):
    model = Morceau
    fields = ['titre','interprete']
    template_name_suffix = '_update_form'

class ArtisteDetailView(DetailView):
    model = Artiste

class ArtisteList(ListView):
    model = Artiste

class ArtisteCreate(CreateView):
    model = Artiste
    fields = ['nom']

class ArtisteDelete(DeleteView):
    model = Artiste
    success_url = reverse_lazy('musiques:artiste_list')

class ArtisteUpdate(UpdateView):
    model = Artiste
    fields = ['nom']
    template_name_suffix = '_update_form'

musiques/templates/musiques/artiste_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Etes-vous sur de vouloir supprimer "{{ object }}"?</p>
    <input type="submit" value="Confirmer">
</form>

musiques/templates/musiques/artiste_detail.html
{% extends "base.html" %}

{% block header %}
           <h2>Détail de l'artiste  {{object.pk}}</h2>
{% endblock %}
{% block content %}
<ul>
    <li>{{object.nom}}</li>
    <li>Nombre de morceaux : {{object.nombre_morceaux}}</li>
    
</ul>
    <a href="{% url 'musiques:artiste_list' %}">
        Revenir a la liste
    </a>

{% endblock %}

musiques/templates/musiques/artiste_form.html
{% extends "base.html" %}

{% block header %}
           <h2>Artiste</h2>
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

musiques/templates/musiques/artiste_list.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}">
{% endblock %}

{% block header %}
<h2>Artistes</h2>
{% endblock %}
{% block content %}

<div class="">
    <div class="card-body">
      <div class="row" style="row-gap: 1rem">
        {% if artiste_list %}
          {% for artiste in artiste_list %}
            <div class="col-sm-6 col-lg-4 col-xl-3">
              <div class="card bg-light text-dark" style="border-radius: 1rem">
                <h5 class="card-header">
                    Artiste n°{{artiste.pk}}
                </h5>
                <div class="card-body">
                  <h5 class="card-text"> {{ artiste.nom }} </h5>
                </div>
                <div class="card-footer d-flex justify-content-between" style="column-gap: 1rem">
                    <a href="{% url 'musiques:artiste-detail' artiste.id %}" class="btn btn-secondary"><i class="fas fa-eye"></i></a>
                    <a href="{% url 'musiques:artiste_update' artiste.id %}" class="btn btn-primary"><i class="fas fa-pen"></i></a>
                    <a href="{% url 'musiques:artiste-delete' artiste.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                  </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <h4 class="container text-warning">Aucun Artiste !</h4>
        {% endif %}
      </div>
    </div>
  </div>
  <a href="{% url 'musiques:artiste_create' %}" class="btn btn-primary mt-3">Ajouter un artiste</a>

{% endblock %}

musiques/templates/musiques/artiste_update_form.html
{% extends "base.html" %}

{% block header %}
           <h2>Mise à jour de l'artiste </h2>
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Mettre à jour">
</form>

{% endblock %}

musiques/templates/musiques/morceau_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Etes-vous sur de vouloir supprimer "{{ object }}"?</p>
    <input type="submit" value="Confirmer">
</form>

musiques/templates/musiques/morceau_detail.html
{% extends "base.html" %}

{% block header %}
           <h2>Informations sur le Morceau n°{{object.pk}}</h2>
{% endblock %}
{% block content %}
<h5>Titre : {{object.titre}}</h5>
<h5>Interprète : {{object.interprete.nom}}</h5>
<!-- si object.date_sortie donne None il affiche non renseigné -->
<h5>Date de sortie : {{object.date_sortie|default:"non renseigné"}}</h5>
<a href="{% url 'musiques:morceau_list' %}">
    Revenir a la liste
</a>

{% endblock %}

musiques/templates/musiques/morceau_form.html
{% extends "base.html" %}

{% block header %}
           <h2>Morceau</h2>
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

musiques/templates/musiques/morceau_list.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}">
{% endblock %}

{% block header %}
<h2>Morceaux</h2>
{% endblock %}
{% block content %}
<div class="">
    <div class="card-body">
      <div class="row" style="row-gap: 1rem">
        {% if morceau_list %}
          {% for morceau in morceau_list %}
            <div class="col-sm-6 col-lg-4 col-xl-3">
              <div class="card bg-light text-dark" style="border-radius: 1rem">
                <h5 class="card-header">
                    {{morceau.pk}} - {{ morceau.interprete.nom }}
                </h5>
                <div class="card-body">
                  <h5 class="card-text"> {{ morceau.titre }}</h5>
                </div>
                <!-- espace entre les 3 -->
                <div class="card-footer d-flex justify-content-between" style="column-gap: 1rem">
                    <a href="{% url 'musiques:morceau-detail' morceau.id %}" class="btn btn-secondary" style=""><i class="fas fa-eye"></i></a>
                    <a href="{% url 'musiques:morceau_update' morceau.id %}" class="btn btn-primary"><i class="fas fa-pen"></i></a>
                    <a href="{% url 'musiques:morceau-delete' morceau.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                  </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <h4 class="container text-warning">Aucun Morceau !</h4>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock %}

musiques/templates/musiques/morceau_update_form.html
{% extends "base.html" %}

{% block header %}
           <h2>Mise à jour du Morceau</h2>
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Mettre à jour">
</form>

{% endblock %}

templates/base.html
<!doctype html>

{% load static %}

<html lang="fr">

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}
    {% block styles %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/png">
    <link rel="icon" sizes="32x32" href="{% static 'favicon-32.png' %}" type="image/png">
    <link rel="icon" sizes="64x64" href="{% static 'favicon-64.png' %}" type="image/png">
    <link rel="icon" sizes="96x96" href="{% static 'favicon-96.png' %}" type="image/png">
    <link rel="icon" sizes="196x196" href="{% static 'favicon-196.png' %}" type="image/png">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'apple-touch-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'apple-touch-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'apple-touch-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'apple-touch-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'apple-touch-icon-144x144.png' %}">
    <meta name="msapplication-TileImage" content="{% static 'favicon-144.png' %}">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <link rel="icon" href="{% static 'animated_favicon.gif' %}" type="image/gif">
    <link rel="stylesheet" href="{% static 'node_modules/bootswatch/dist/superhero/bootstrap.min.css' %}">
    {% endblock %}
</head>

<body>
   <!-- navbar en blue -->
    <header class="mb-3">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <a class="navbar-brand" href="/musiques/">Hayz Music</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a class="nav-link" href="{% url 'musiques:morceau_list' %}">Morceaux</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'musiques:morceau_create' %}">Créer nouveau morceau</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'musiques:artiste_list' %}">Artistes</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'musiques:artiste_create' %}">Créer nouveau artiste</a></li>
            </ul>
          </div>
        </nav>
      </header>
    <main role="main" class="container top-pushed mt-4">
        <div class="jumbotron">
            {% block header %}{% endblock %}
            {% block content %}
            {% endblock %}
        </div>
    </main>
    {% block js %}
    <script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'node_modules/popper.js/dist/popper.min.js' %}"></script>

    {% endblock %}
</body>

</html>